---
title: "Example Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(leaflet)
library(scales)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart 1

```{r}
qplot(data=trees, x=Girth, y= Height, main="Trees data")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart 2

```{r}
# Read the CSV file with correct parameters
ga_data <- read.csv("D:/SSU/NewVsRetruning.csv", sep=",", header=TRUE, stringsAsFactors = FALSE)


# Data cleaning and preparation
# Create a data frame with user types and sessions
ga_data.toPlot <- data.frame(userType = c("New Visitor", "Returning Visitor"), 
                             sessions = c(ga_data$Sessions[1], ga_data$Sessions[2]))

# Remove commas from sessions and convert to numeric
ga_data.toPlot$sessions <- as.numeric(gsub(",", "", ga_data.toPlot$sessions))

# Print to verify conversion
print(ga_data.toPlot)

# Calculate percentage
ga_data.toPlot$percentage <- ga_data.toPlot$sessions / sum(ga_data.toPlot$sessions)

# Check for and handle missing or non-numeric values
ga_data.toPlot <- na.omit(ga_data.toPlot)
ga_data.toPlot <- ga_data.toPlot[!is.na(ga_data.toPlot$sessions), ]



# Plot
ggplot(data = ga_data.toPlot, aes(x = factor(userType, levels = c("New Visitor", "Returning Visitor")), y = sessions, fill = userType)) + 
  geom_bar(width = 0.6, stat = "identity") +  
  geom_text(aes(y = sessions / 2, label = percent(percentage)), size = 5) +
  labs(title = "Sessions by User Type", x = "User Type", y = "Number of Sessions") +
  scale_fill_manual(values = c("New Visitor" = "blue", "Returning Visitor" = "green")) +
  theme_minimal()

```

### Chart C

```{r}
library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  addMarkers(lng=174.768, lat=-36.852, popup="Hello World")
```

